ProductsAndCategories/Models/Association.cs
#pragma warning disable CS8618

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ProductsAndCategories.Models;

public class Association
{
    [Key]
    public int AssociationId { get; set; }

    public int ProductId { get; set; }

    public int CategoryId { get; set; }

    public Product? Product { get; set; }
    public Category? Category { get; set; }
}

ProductsAndCategories/Models/Catgegory.cs
#pragma warning disable CS8618

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ProductsAndCategories.Models;

public class Category
{
    [Key]
    public int CategoryId { get; set; }

    [Required(ErrorMessage ="is required")]
    [MinLength(2, ErrorMessage ="must be at least 2 characters")]
    [MaxLength(45, ErrorMessage ="must be 45 characters or less")]
    public string Name { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public List<Association> Products { get; set; } = new List<Association>();
}

ProductsAndCategories/Models/DatabaseContext.cs
#pragma warning disable CS8618
/* 
Disabled Warning: "Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable."
We can disable this safely because we know the framework will assign non-null values when it constructs this class for us.
*/
using Microsoft.EntityFrameworkCore;
namespace ProductsAndCategories.Models;
// the MyContext class representing a session with our MySQL database, allowing us to query for or save data
public class DatabaseContext : DbContext 
{ 
    public DatabaseContext(DbContextOptions options) : base(options) { }
    // the "Monsters" table name will come from the DbSet property name
    //public DbSet<Monster> Monsters { get; set; }
    public DbSet<Category> Categories { get; set; }
    public DbSet<Product> Products { get; set; }
    public DbSet<Association> Associations { get; set; }
}

ProductsAndCategories/Models/ErrorViewModel.cs
namespace ProductsAndCategories.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ProductsAndCategories/Models/Product.cs
#pragma warning disable CS8618

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ProductsAndCategories.Models;

public class Product 
{
    [Key]
    public int ProductId { get; set; }

    [Required(ErrorMessage ="is required")]
    [MinLength(2, ErrorMessage ="must be at least 2 characters")]
    [MaxLength(45, ErrorMessage ="must be 45 characters or less")]
    public string Name { get; set; }

    [Required]
    public double Price { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public List<Association> Categories { get; set; } = new List<Association>();
}

ProductsAndCategories/Controllers/CategoryController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProductsAndCategories.Models;

namespace ProductsAndCategories.Controllers;

public class CategoryController : Controller
{

    private DatabaseContext _context;

    public CategoryController(DatabaseContext context)
    {
        _context = context;
    }

    [HttpGet("/categories/all")]
    public IActionResult All()
    {

        List<Category> allCategories = new List<Category>();
        allCategories = _context.Categories.ToList();

        return View("All", allCategories);

    }

    [HttpGet("/categories/new")]
    public IActionResult New()
    {
        return View("New");
    }


    [HttpPost("/categories/create")]
    public IActionResult Create(Category newCategory)
    {
        if (ModelState.IsValid)
        {
            return New();
        }
        _context.Categories.Add(newCategory);
        _context.SaveChanges();
        return All();
    }


    [HttpGet("/categories/{productId}/details")]
    public IActionResult ShowDetails(int categoryId)
    {
        var categoryWithAssociations = _context.Categories
        .Include(category => category.Products)
            .ThenInclude(association => association.Product)
        .FirstOrDefault(category => category.CategoryId == categoryId);

        List<Product> allProducts = new List<Product>();
        allProducts = _context.Products.ToList();
        ViewBag.allProducts = allProducts;
        ViewBag.categoryId = categoryId;
        
        // List<Category> allCategories = new List<Category>();
        // allCategories = _context.Categories.ToList();
        // ViewBag.allCategories = allCategories;

        if (categoryWithAssociations != null)
        {
            ViewBag.existingProducts = categoryWithAssociations.Products.ToList();
            return View("Details", categoryWithAssociations);
        }
        return All();
    }

    [HttpPost("/categories/{categoryId}/associations/add")]
    public IActionResult Associate(Association newAssociation, int categoryId)
    {
        if (ModelState.IsValid == false)
        {
            return ShowDetails(categoryId);
        }

        _context.Associations.Add(newAssociation);
        _context.SaveChanges();
        return ShowDetails(categoryId);
    }
    
}

ProductsAndCategories/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProductsAndCategories.Models;

namespace ProductsAndCategories.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ProductsAndCategories/Controllers/ProductController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProductsAndCategories.Models;

namespace ProductsAndCategories.Controllers;

public class ProductController : Controller
{
    private DatabaseContext _context;

    public ProductController(DatabaseContext context)
    {
        _context = context;
    }

    [HttpGet("/products/all")]
    public IActionResult All()
    {
        List<Product> allProducts = new List<Product>();
        allProducts = _context.Products.ToList();

        return View("All", allProducts);
    }

    [HttpGet("/products/new")]
    public IActionResult New()
    {
        return View("New");
    }

    [HttpPost("/products/create")]
    public IActionResult Create(Product newProduct)
    {
        if (ModelState.IsValid == false)
        {
            return New();
        }

        _context.Products.Add(newProduct);
        _context.SaveChanges();
        return All();
    }

    [HttpGet("/products/{productId}/details")]
    public IActionResult ShowDetails(int productId)
    {
        Product? productWithAssociations = _context.Products
        .Include(product => product.Categories)
            .ThenInclude(association => association.Category)
        .FirstOrDefault(product => product.ProductId == productId);

        // List<Product> allProducts = new List<Product>();
        // allProducts = _context.Products.ToList();
        // ViewBag.allProducts = allProducts;

        List<Category> allCategories = new List<Category>();
        allCategories = _context.Categories.ToList();
        ViewBag.allCategories = allCategories;

        if (productWithAssociations != null)
        {
            return View("Details", productWithAssociations);
        }
        return All();
    }
    


}

ProductsAndCategories/Views/Category/All.cshtml
@model List<Category>
<h1>Categories</h1>
<a asp-controller="Category" asp-action="New">New Category</a>

<ul>

    @{
        foreach (Category category in Model)
        {
            <div>
                <li>@category.Name - - <a asp-controller="Category" asp-action="ShowDetails" asp-route-categoryId="@category.CategoryId">See Details</a></li>
            </div>
            
        }
    }

</ul>

ProductsAndCategories/Views/Category/Details.cshtml
@model Category

<h1>Category Details</h1>
<h3>@Model.Name</h3>
<h4>Products in Category</h4>
<ul>
    @{
        foreach (var association in Model.Products)
        {
            if (association.Product != null)
            {
                <li>@association.Product.Name</li>
            }
            
            
        }

        
        
    }
</ul>

@{
    Association newAssociation = new Association();
}
<partial name="_Association" model="newAssociation" view-data="ViewData"></partial>

ProductsAndCategories/Views/Category/New.cshtml
@model Category

 <form class="shadow p-3 rounded" asp-controller="Category" asp-action="Create" method="POST">
    <div class="mb-3">
      <label asp-for="Name"></label>
      <span asp-validation-for="Name" class="text-danger font-weight-bold">
      </span>
      <input class="form-control" asp-for="Name">
    </div>

    <button class="btn btn-success">Submit</button>
 </form>

ProductsAndCategories/Views/Category/_Association.cshtml
@model Association


<form class="shadow p-3 rounded" asp-controller="Category" asp-action="Associate" asp-route-categoryId="@ViewBag.categoryId" method="POST">
    <select>
        @{
            List<Product> allProducts = new List<Product>();
            allProducts = ViewBag.allProducts;

            List<Product> existingProducts = new List<Product>();
            existingProducts = ViewBag.existingProducts;

            foreach (Product product in allProducts)
            {
                if (existingProducts.Contains(product) == false)
                {
                    <option value="@product.ProductId">@product.Name</option>
                }
            }

                
        }
    </select>

    <button class="btn btn-success">Add Association</button>
</form>

ProductsAndCategories/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProductsAndCategories/Views/Product/All.cshtml
@model List<Product>
<h1>Products</h1>
<a asp-controller="Product" asp-action="New">New Product</a>

<ul>

    @{
        foreach (Product product in Model)
        {
            <div>
                <li>@product.Name - - <a asp-controller="Category" asp-action="ShowDetails" asp-route-productId="@product.ProductId">See Details</a></li>
            </div>
            
        }
    }

</ul>

ProductsAndCategories/Views/Product/New.cshtml
@model Product

 <form class="shadow p-3 rounded" asp-controller="Product" asp-action="Create" method="POST">
    <div class="mb-3">
      <label asp-for="Name"></label>
      <span asp-validation-for="Name" class="text-danger font-weight-bold">
      </span>
      <input class="form-control" asp-for="Name">
    </div>

    <div class="mb-3">
      <label asp-for="Price"></label>
      <span asp-validation-for="Price" class="text-danger font-weight-bold">
      </span>
      <input class="form-control" asp-for="Price">
    </div>

    <button class="btn btn-success">Submit</button>
 </form>

ProductsAndCategories/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductsAndCategories</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductsAndCategories.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductsAndCategories</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="All">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="All">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProductsAndCategories - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>